/**
 * Etiquetas legibles para las acciones de `audit_log` (D-218/RF-S2/M3). Lista cerrada de lo
 * que el código escribe hoy (censo por grep de `action: '...'` en `apps/api/src`); lo que no
 * esté acá cae en `humanizeAction`, que nunca deja una acción sin leer aunque sea menos
 * prolija — una acción nueva no debería poder hacer que el visor la muestre en blanco.
 */
const AUDIT_ACTION_LABELS: Record<string, string> = {
  'auth.login': 'Inicio de sesión',
  'auth.login.failed': 'Intento de inicio de sesión fallido',
  'auth.logout': 'Cierre de sesión',
  'auth.password.changed': 'Cambio de contraseña propia',
  'catalog.create': 'Alta de producto',
  'catalog.update': 'Edición de producto',
  'catalog.price-list-import.confirm': 'Carga masiva de precios de lista confirmada',
  'catalog.price-list-import.revert': 'Carga masiva de precios de lista revertida',
  'coils.cancel': 'Anulación de bobina',
  'coils.close': 'Cierre de bobina',
  'coils.cutting-cost': 'Costo de corte aplicado a bobina',
  'coils.landed-cost': 'Costo de importación aplicado a bobina',
  'coils.open': 'Reapertura de bobina',
  'coils.scrap': 'Merma registrada en bobina',
  'coils.scrap-cancel': 'Anulación de merma de bobina',
  'coils.split': 'Partido de bobina',
  'coils.split-revert': 'Reversa de partido de bobina',
  'coils.update': 'Edición de bobina',
  'colors.create': 'Alta de color',
  'colors.update': 'Edición de color',
  'customers.create': 'Alta de cliente',
  'customers.update': 'Edición de cliente',
  'cutting.cancel': 'Anulación de orden de corte',
  'cutting.receive': 'Recepción de corte',
  'cutting.receive-reverse': 'Reversa de recepción de corte',
  'cutting.send': 'Envío a corte tercerizado',
  'exchange-rates.manual-set': 'Tipo de cambio fijado a mano',
  'finishes.create': 'Alta de acabado',
  'finishes.update': 'Edición de acabado',
  'imports.initial-inventory': 'Carga de inventario inicial de bobinas',
  'imports.initial-inventory-products': 'Carga de inventario inicial de productos',
  'invoicing.credit-note.create': 'Nota de crédito creada',
  'invoicing.dispatch.create': 'Despacho creado',
  'invoicing.dispatch.reverse': 'Despacho revertido',
  'invoicing.dispatch-note.create': 'Guía de remisión creada',
  'invoicing.document.correct': 'Comprobante corregido y reemitido',
  'invoicing.document.create': 'Comprobante creado',
  'invoicing.document.discard-draft': 'Borrador de comprobante descartado',
  'invoicing.document.issue': 'Comprobante emitido',
  'invoicing.document.register-manual': 'Comprobante manual registrado',
  'invoicing.document.retry': 'Reintento de envío de comprobante',
  'invoicing.document.update-issue-date': 'Fecha de emisión de comprobante manual corregida',
  'invoicing.document.void': 'Comprobante dado de baja',
  'invoicing.document.void-confirmed': 'Baja de comprobante confirmada por SUNAT',
  'invoicing.document.void-reconciled': 'Baja de comprobante reconciliada',
  'invoicing.document.void-rejected': 'Baja de comprobante rechazada',
  'invoicing.import.annul': 'Comprobante importado/manual anulado internamente',
  'invoicing.payment': 'Cobro registrado',
  'invoicing.payment-reverse': 'Reversa de cobro',
  'invoicing.series.create': 'Alta de serie de comprobante',
  'invoicing.series.toggle': 'Serie de comprobante activada o desactivada',
  'invoicing.settings.update': 'Configuración de facturación actualizada',
  'pos.cash-session.close': 'Cierre de caja',
  'pos.cash-session.open': 'Apertura de caja',
  'pos.sale.create': 'Venta de mostrador',
  'pos.sale.void': 'Anulación de venta de mostrador',
  'pos.sale.void-start': 'Anulación de venta de mostrador iniciada',
  'pricing.update': 'Márgenes de precio actualizados',
  'production.cancel': 'Anulación de orden de producción',
  'production.close': 'Cierre de orden de producción',
  'production.consume': 'Consumo registrado en orden de producción',
  'production.create': 'Orden de producción creada',
  'production.release': 'Liberación de orden de producción',
  'production.reopen': 'Reapertura de orden de producción',
  'production.report': 'Reporte de producción',
  'production.report-reverse': 'Reversa de reporte de producción',
  'production.roofing.cancel': 'Anulación de orden de coberturas',
  'production.roofing.close': 'Cierre de orden de coberturas',
  'production.roofing.create': 'Orden de coberturas creada',
  'production.roofing.create_batch': 'Lote de órdenes de coberturas creado',
  'production.roofing.drafts-commit': 'Borrador de reportes de coberturas confirmado',
  'production.roofing.mount': 'Bobina montada en producción de coberturas',
  'production.roofing.plan': 'Plan de corte de coberturas definido',
  'production.roofing.release': 'Liberación de orden de coberturas',
  'production.roofing.reopen': 'Reapertura de orden de coberturas',
  'production.roofing.report': 'Reporte de producción de coberturas',
  'production.roofing.report-reverse': 'Reversa de reporte de producción de coberturas',
  'purchases.cancel': 'Anulación de compra',
  'purchases.create': 'Compra registrada',
  'purchases.payment': 'Pago a proveedor registrado',
  'purchases.payment-reverse': 'Reversa de pago a proveedor',
  'purchases.receive': 'Recepción de compra',
  'purchases.update-document': 'Documento de compra editado',
  'purchases.xml-preview': 'XML de compra previsualizado',
  'sales.order.add-items': 'Líneas agregadas a pedido',
  'sales.order.cancel': 'Cancelación de pedido',
  'sales.order.confirm': 'Confirmación de pedido',
  'sales.order.customer': 'Cliente de pedido cambiado',
  'sales.order.item-price': 'Precio de línea de pedido editado',
  'sales.order.item-qty': 'Cantidad de línea de pedido editada',
  'sales.order.promised-delivery-date': 'Fecha de entrega prometida cambiada',
  'sales.quotation.cancel': 'Cancelación de cotización',
  'sales.quotation.create': 'Cotización creada',
  'sales.quotation.duplicate': 'Cotización duplicada',
  'sales.quotation.expire': 'Cotización vencida',
  'sales.quotation.recalculate-temporary': 'Reserva temporal de cotización recalculada',
  'sales.quotation.release-temporary': 'Reserva temporal de cotización liberada',
  'sales.quotation.reserve-temporary': 'Reserva temporal de cotización creada',
  'sales.quotation.update': 'Cotización editada',
  'sales.reservation.release': 'Liberación manual de reserva',
  'sales.settings.update': 'Configuración de ventas actualizada',
  'suppliers.create': 'Alta de proveedor',
  'suppliers.update': 'Edición de proveedor',
  'users.create': 'Alta de usuario',
  'users.deactivate': 'Desactivación de usuario',
  'users.password.reset': 'Restablecimiento de contraseña',
  'users.role.change': 'Cambio de rol de usuario',
  'users.update': 'Edición de usuario',
};

const CHANGELOG_ACTION_LABELS: Record<string, string> = {
  sales_price_change: 'Cambio de precio de línea',
  product_list_price_change: 'Cambio de precio de lista',
  fiscal_document_issue_date_change: 'Corrección de fecha de emisión',
};

/** Etiquetas del filtro "Tipo de entidad" del visor — cubre todo `AUDIT_ENTITY_TYPES`. */
export const AUDIT_ENTITY_TYPE_LABELS: Record<string, string> = {
  cash_sessions: 'Sesiones de caja',
  coil_splits: 'Partidos de bobina',
  coils: 'Bobinas',
  colors: 'Colores',
  customer_payments: 'Cobros',
  customers: 'Clientes',
  cutting_orders: 'Órdenes de corte',
  dispatches: 'Despachos',
  exchange_rates: 'Tipo de cambio',
  finishes: 'Acabados',
  fiscal_documents: 'Comprobantes',
  fiscal_series: 'Series de comprobante',
  invoicing_settings: 'Configuración de facturación',
  pos_sales: 'Ventas de mostrador',
  pricing_settings: 'Configuración de precios',
  product_boms: 'Recetas de producto',
  production_orders: 'Órdenes de producción',
  products: 'Productos',
  purchases: 'Compras',
  quotations: 'Cotizaciones',
  reservations: 'Reservas',
  sales_orders: 'Pedidos',
  sales_settings: 'Configuración de ventas',
  sessions: 'Sesiones',
  suppliers: 'Proveedores',
  users: 'Usuarios',
};

/** Nunca deja una acción sin leer: lo que no está en el mapa se separa por `.`/`-`/`_`. */
function humanizeAction(action: string): string {
  const words = action.split(/[._-]/).filter(Boolean).join(' ');
  return words.charAt(0).toUpperCase() + words.slice(1);
}

export function auditActionLabel(action: string, source: string): string {
  if (source !== 'audit_log') return CHANGELOG_ACTION_LABELS[source] ?? humanizeAction(action);
  return AUDIT_ACTION_LABELS[action] ?? humanizeAction(action);
}

export function auditEntityTypeLabel(entityType: string): string {
  return AUDIT_ENTITY_TYPE_LABELS[entityType] ?? humanizeAction(entityType);
}
